# Generated by Django 6.0 on 2025-12-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_alter_order_buisiness_user_alter_order_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buisiness_user',
            new_name='business_user',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='features',
            field=models.JSONField(default=('Logo Design',)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='premium', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='revisions',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
    ]
