# Generated by Django 6.0 on 2025-12-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_remove_offer_offer_id_offer_id_alter_offer_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferDetail',
            new_name='OfferDetails',
        ),
    ]
