# Generated by Django 6.0 on 2025-12-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_rename_offerdetail_offerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='delivery_time_in_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
