# Generated by Django 6.0 on 2025-12-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_alter_offer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
