# Generated by Django 6.0 on 2025-12-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_alter_offerdetails_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerdetails',
            options={'verbose_name': 'Offer Detail'},
        ),
    ]
